# -*- coding: utf-8 -*-
"""1.5T_Study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDKrwuwunNEDRBc6n6F7jne9vKTVp6l3

#Installazione libreria dipy + import librerie necessarie + file upload
"""

pip install dipy

# Import librerie necessarie

import numpy as np
import nibabel as nib
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt
import os
from scipy.stats import chi2

from google.colab import drive
drive.mount('/content/drive')

# Percorso della cartella contenente i file .h5
folder_path = '/content/drive/MyDrive/LAB_2/1.5T/1'

# Funzione per caricare un file NIfTI
def load_nii_file(folder_path, file_name):
    file_path = os.path.join(folder_path, file_name)
    if os.path.exists(file_path):
        return nib.load(file_path)
    else:
        raise FileNotFoundError(f'{file_name} non trovato nel percorso specificato.')

# Lista dei file .nii da caricare
file_names = ["dwi.nii", "prova.nii", "fetal_mask.nii", "maternal_mask.nii", "background_mask.nii"]

# Caricamento delle immagini NIfTI
try:
    dwi_image = load_nii_file(folder_path, 'dwi.nii')
    #dwi_image = nib.load('dwi.nii')
    mask_image = load_nii_file(folder_path, 'prova.nii')
    #mask_image = nib.load('prova.nii')

    fetal_mask_image = load_nii_file(folder_path, 'fetal_mask.nii')
    #fetal_mask_image = nib.load('fetal_mask.nii')
    maternal_mask_image = load_nii_file(folder_path, 'maternal_mask.nii')
    #maternal_mask_image = nib.load('maternal_mask.nii')

    background_mask_image = load_nii_file(folder_path, 'background_mask.nii')


    # Estrazione dei dati dalle immagini
    dwi_data = dwi_image.get_fdata()
    mask_data = mask_image.get_fdata()
    fetal_mask_data = fetal_mask_image.get_fdata()
    maternal_mask_data = maternal_mask_image.get_fdata()
    background_mask_data = background_mask_image.get_fdata()


    # Verifica delle dimensioni
    assert dwi_data.ndim == 4, "L'immagine dwi deve essere 4-dimensionale"
    assert mask_data.shape == dwi_data.shape[:3], "La maschera deve avere le stesse dimensioni spaziali dell'immagine dwi"
    assert fetal_mask_data.shape == dwi_data.shape[:3], "La maschera fetale deve avere le stesse dimensioni spaziali dell'immagine dwi"
    assert maternal_mask_data.shape == dwi_data.shape[:3], "La maschera materna deve avere le stesse dimensioni spaziali dell'immagine dwi"
    assert background_mask_data.shape == dwi_data.shape[:3], "La maschera di background deve avere le stesse dimensioni spaziali dell'immagine dwi"

    # Stampa per confermare il caricamento
    print(f'dwi.nii dimensioni: {dwi_data.shape}')
    print(f'prova.nii dimensioni: {mask_data.shape}')
    print(f'fetal_mask.nii dimensioni: {fetal_mask_data.shape}')
    print(f'maternal_mask.nii dimensioni: {maternal_mask_data.shape}')
    print(f'background_mask.nii dimensioni: {maternal_mask_data.shape}')

except FileNotFoundError as e:
    print(e)

"""# **Parte 1**: **HEATMAPS**

## Inizializzazione

Funzione di fitting per il **monoexponential** model:

$S(b) = S(0) e^{-bD}$

Funzione di fitting per **IVIM** model:

$S(b) = S(0)\left[f e^{-bD^*} + (1-f) e^{-bD}\right]$

Funzione di fitting per il **two perfusion** model:

$ S(b) = S(0) \left[ f_1 e^{-(D_1^* + D_2^* + D)b} + f_2 e^{-(D_2^* + D)b} + (1 - f_1 - f_2) e^{-Db} \right] $

[Link all'articolo](https://iris.uniroma1.it/retrieve/32d4c307-bb1f-4da9-b63f-a9eecc79cb48/Maiuro_Two-compartment-perfusion_2023.pdf):
"""

# PART I: MASK

masked_dwi_data = np.zeros(dwi_data.shape)
dwi_norm = np.zeros(dwi_data.shape)

# Mask cration
for i in range(10):
  dwi_norm[:,:,:,i] = dwi_data[:,:,:,i] * mask_data

bool_mask = mask_data != 0
roi = dwi_data[bool_mask,:]
mean_roi = np.mean(roi, axis=0)
error_roi = np.std(roi, axis=0)/np.sqrt(roi.shape[1])
"""
x,y,z = np.nonzero(masked_dwi_data[:,:,:,0])
for i in range(10):
  for k in range(int(x.shape[0])):
    dwi_norm[x[k],y[k],z[k],i] = masked_dwi_data[x[k],y[k],z[k],i]/masked_dwi_data[x[k],y[k],z[k],0]
"""

# PARTE II: FIT

def monoexponential_model(b,D,S0):
  return (S0*np.exp(-b*D))

# Calcolo l'incertezza dei parametri di fitting utilizzando la matrice di covarianza
def uncertainty_monoexponential(b, D, S0, pcov):
    return (np.sqrt(np.diag(pcov)))

class IVIM():
  def __init__(self, D:float): #parametro D fissato
    self.D = D

  def uncertainty(self, b, pcov):
        return np.sqrt(np.diag(pcov))

  def function(self,b,f,D_star,S0):
    return S0* (f * np.exp(-b*D_star) + (1-f)*np.exp(-b*self.D))

  def function_alpha(self,b,f,D_star,S0,alpha):
    return S0* (f * np.exp(-b*D_star) + alpha * (1-f)*np.exp(-b*self.D))

class Perfusion():
    def __init__(self, D:float, f:float): #parametri D ed f fissati
        self.D = D
        self.f = f

    def function2(self, b, D1_star, D2_star, f1, S0):
      return S0 * (f1 * np.exp(-(D1_star + D2_star + self.D) * b) +
                  (self.f - f1) * np.exp(-(D2_star + self.D) * b) +
                   (1 - self.f) * np.exp(-self.D * b))

    def function2_alpha(self, b, D1_star, D2_star, f1, S0):
      return S0 * (f1 * np.exp(-(D1_star + D2_star + self.D) * b) +
                  (self.f - f1) * np.exp(-(D2_star + self.D) * b) +
                  self.alpha * (1 - self.f) * np.exp(-self.D * b))

    def uncertainty(self, b, pcov):
        return np.sqrt(np.diag(pcov))

# Lista dei valori di b (b-values)
# moltiplicati per un fattore 10^-3 per questioni dimensionali
b_values = np.array([0, 10 , 30, 50, 75, 100, 200, 400, 700, 1000]) * 10**-3
print("b_values = ", b_values, "X 10^3 s/mm^2")
print("\nUltimi 4 b_values = ", b_values[-4:], "X 10^3 s/mm^2")

# Boundary conditions
bounds_mono = ([0.01, 0], [3, np.inf])#range di D, in [mm^2/s], ed S0
bounds_IVIM = ([0.00000001, 5, 0], [1, 10000, np.inf]) #primo: f [adimensionale]; secondo: D_star[mm^2/s]; terzo: S0

#bounds_perfusion = ([100, 5, 0], [10000, 100, 1]) #primo: D1_star(max messo come D_star) [mm^2/s]; secondo: D2_star[mm^2/s]; terzo: f1 [adimensionale

#Initial conditions
init_mono = [0.1,-np.inf]
init_ivim = [0.01,100,-np.inf]
init_perfusion = [101,10,0,-np.inf]

# Preallocazione delle mappe per i parametri

param_maps_monoexponential = {
    'D': np.zeros(mask_data.shape)
}

param_maps_IVIM = {
    'f': np.zeros(mask_data.shape),
    'D_star': np.zeros(mask_data.shape),
    #'alpha': np.zeros(mask_data.shape)
}

param_maps_perfusion = {
    'D1_star': np.zeros(mask_data.shape),
    'D2_star': np.zeros(mask_data.shape),
    'f1': np.zeros(mask_data.shape),
    'f2': np.zeros(mask_data.shape)
}

dwi_norm_mono=np.zeros([192,192,19,4])

for i in range(4):
  j=i+6
  dwi_norm_mono[:,:,:,i] = dwi_norm[:,:,:,j]

b_mono =  b_values[-4:] #uso solo ultimi 4 b_values, quindi: 200, 400, 700, 1000

# Loop su ogni voxel per il fitting dei parametri, MONOEXPONENTIAL MODEL:
for i in range(mask_data.shape[0]):
    for j in range(mask_data.shape[1]):
        for k in range(mask_data.shape[2]):
          if mask_data[i,j,k] != 0:
                try:
                  #if init_mono[-1]== -np.inf:
                    init_mono[-1] = dwi_norm[i,j,k,0]
                    popt, _ = curve_fit(monoexponential_model, b_values[-4:], dwi_norm[i,j,k,-4:], init_mono, bounds=bounds_mono)
                    param_maps_monoexponential['D'][i, j, k] = popt[0]
                    #init_mono[-1] = -np.inf
                except RuntimeError:
                    # Se il fitting non converge si lasciano i parametri a 0
                    pass

b_IVIM = b_values # uso tutti i b_values

# Loop su ogni voxel per il fitting dei parametri, IVIM class MODEL:
for i in range(mask_data.shape[0]):
    for j in range(mask_data.shape[1]):
        for k in range(mask_data.shape[2]):
          if mask_data[i,j,k] != 0:

                try:
                    init_ivim[-1] = dwi_norm[i,j,k,0]
                    ivim = IVIM(param_maps_monoexponential['D'][i, j, k])
                    popt, _ = curve_fit(ivim.function, b_IVIM, dwi_norm[i,j,k,], init_ivim, bounds=bounds_IVIM)
                    param_maps_IVIM['f'][i, j, k] = popt[0]
                    param_maps_IVIM['D_star'][i, j, k] = popt[1]
                    #param_maps_IVIM['alpha'][i, j, k] = popt[-1]
                    #init_ivim[-1] = -np.inf
                except RuntimeError:
                    continue

init_perfusion = [101,10,0,-np.inf] # initial conditions
b_perfusion = b_values # using all 10 b_values

# Loop over each voxel for fitting the parameters, TWO-PERFUSION class MODEL:
for i in range(mask_data.shape[0]):
    for j in range(mask_data.shape[1]):
        for k in range(mask_data.shape[2]):
            if mask_data[i,j,k] != 0:
                try:
                    init_perfusion[-1] = dwi_norm[i,j,k,0] #setting S(0)
                    if param_maps_IVIM['f'][i, j, k] == 0.0:

                    bounds_perfusion = ([100, 5, 0, 0], [10000, 100, param_maps_IVIM['f'][i, j, k], np.inf])
                    perfusion_model = Perfusion(param_maps_monoexponential['D'][i, j, k], param_maps_IVIM['f'][i, j, k])
                    popt, _ = curve_fit(perfusion_model.function2, b_perfusion, dwi_norm[i,j,k,], init_perfusion, bounds=bounds_perfusion)
                    param_maps_perfusion['D1_star'][i, j, k] = popt[0]
                    param_maps_perfusion['D2_star'][i, j, k] = popt[1]
                    param_maps_perfusion['f1'][i, j, k] = popt[2]
                    param_maps_perfusion['f2'][i, j, k] = param_maps_IVIM['f'][i, j, k] - popt[2]

                except RuntimeError:
                    continue
                except ValueError:
                  continue

"""## Creazione heatmaps"""

# PARTE III: CREAZIONE DELLE HEATMAPS

# Setto il tipo di colormap che voglio, cercando di massimizzare contrasto
colormap = 'viridis'

def plot_heatmap(param_map, title, filename, unit=''):
    plt.figure(figsize=(10, 8))
    plt.imshow(param_map[:, :, param_map.shape[2] // 2], cmap=colormap, interpolation='nearest')
    cbar = plt.colorbar()
    if unit:  # Aggiunge le unità di misura solo se sono specificate
        cbar.set_label(unit)  # Imposta le unità di misura sull'asse della colorbar
    plt.title(title)
    plt.savefig(filename)
    plt.close()

# Creazione directory per salvare le mappe
output_dir = 'param_maps'
os.makedirs(output_dir, exist_ok=True)

# Plot delle heatmap per ciascun parametro monoexponential
for param, param_map in param_maps_monoexponential.items():
    unit = '$\\times 10^{-3}$ mm$^2$/s' if param == 'D' else ''  # Aggiungi le unità di misura solo per D
    plot_heatmap(param_map, f'Heatmap of {param}', os.path.join(output_dir, f'{param}_heatmap.pdf'), unit=unit)

# Plot delle heatmap per ciascun parametro IVIM
for param, param_map in param_maps_IVIM.items():
    unit = '$\\times 10^{-3}$ mm$^2$/s' if param in ['D_star'] else ''  # Aggiungi le unità di misura solo per D_star
    plot_heatmap(param_map, f'Heatmap of {param}', os.path.join(output_dir, f'{param}_heatmap.pdf'), unit=unit)

# Plot delle heatmap per ciascun parametro Two-Perfusion
for param, param_map in param_maps_perfusion.items():
    unit = '$\\times 10^{-3}$ mm$^2$/s' if param in ['D1_star', 'D2_star'] else ''  # Aggiungi le unità di misura solo per D1_star e D2_star
    plot_heatmap(param_map, f'Heatmap of {param}', os.path.join(output_dir, f'{param}_heatmap.pdf'), unit=unit)

print("Elaborazione completata: mappe salvate in formato pdf nella directory 'param_maps'.")

"""### Visualizzazione mappe ottenute"""

def plot_images(param_maps_IVIM, param_maps_perfusion, param_maps_monoexponential):
    plt.figure(figsize=(18, 16))

    # Prima riga - Parametri IVIM
    params_IVIM = ['D_star', 'f']
    for i, param in enumerate(params_IVIM, 1):
        unit = '$\\times 10^{-3}$ mm$^2$/s' if param == 'D_star' else ''  # Aggiungi le unità di misura solo per D_star
        plt.subplot(3, 3, i)
        plt.imshow(param_maps_IVIM[param][:, :, param_maps_IVIM[param].shape[2] // 2], cmap=colormap)
        cbar = plt.colorbar()
        if unit:
            cbar.set_label(unit)  # Imposta le unità di misura sull'asse della colorbar
        plt.title(f'{param} Map')

    # Seconda riga - Parametri Two-Perfusion
    params_perfusion = ['D1_star', 'D2_star', 'f1']
    for i, param in enumerate(params_perfusion, 4):
        unit = '$\\times 10^{-3}$ mm$^2$/s' if param in ['D1_star', 'D2_star'] else ''  # Aggiungi le unità di misura solo per D1_star e D2_star
        plt.subplot(3, 3, i)
        plt.imshow(param_maps_perfusion[param][:, :, param_maps_perfusion[param].shape[2] // 2], cmap=colormap)
        cbar = plt.colorbar()
        if unit:
            cbar.set_label(unit)  # Imposta le unità di misura sull'asse della colorbar
        plt.title(f'{param} Map')

    # Terza riga - Parametri monoexponential e Two-Perfusion
    param_mono = 'D'
    plt.subplot(3, 3, 7)
    plt.imshow(param_maps_monoexponential[param_mono][:, :, param_maps_monoexponential[param_mono].shape[2] // 2], cmap=colormap)
    cbar = plt.colorbar()
    cbar.set_label('$\\times 10^{-3}$ mm$^2$/s')  # Imposta le unità di misura sull'asse della colorbar
    plt.title(f'{param_mono} Map')

    param_f2 = 'f2'
    plt.subplot(3, 3, 8)
    plt.imshow(param_maps_perfusion[param_f2][:, :, param_maps_perfusion[param_f2].shape[2] // 2], cmap=colormap)
    plt.colorbar()
    plt.title(f'{param_f2} Map')

    plt.tight_layout()
    plt.show()

plot_images(param_maps_IVIM, param_maps_perfusion, param_maps_monoexponential)

"""# **Parte 2**: **FIT**

Akaike information criterion (AIC) is defined as:

$ AIC = N_b \cdot log(MSE) \cdot \dfrac{ 2k (k +1)}{N_b - k - 1} $

where $N_b$ is the number of $b$-values, $MSE$ is the mean squared error, and $k$ is the number of the model’s parameters.

$k=4$ per 2-perf; $k=4$ per IVIM; $k=2$ per mononexponential
"""

# Function to calculate: Akaike Information Criterion (AIC)
def calculate_AIC(MSE, k, N_b):
    return N_b * np.log(MSE) + 2 * k * (k + 1) / (N_b - k - 1)

# Function to calculate: mean and standard deviation within ROI (regions of interes)
def calculate_mean_and_std(param_map, mask_data):
    # Calculate mean within ROI
    mean_roi = np.mean(param_map[mask_data != 0])

    # Calculate standard deviation corrected for the number of voxels
    std_roi = np.std(param_map[mask_data != 0], ddof=1) / np.sqrt(np.count_nonzero(mask_data))
    return mean_roi, std_roi

# Numero di parametri dei modelli
k_perfusion = 4
k_IVIM = 3
k_mono = 2

# Numero di b-values utilizzati nel fitting
N_b_perf = 10 #len(b_perfusion)
N_b_IVIM = 10 #len(b_IVIM)
N_b_mono = 4 #len(b_mono)

"""To segment the placenta into fetal and maternal parts based on the f, f1, and f2 maps, we can use thresholding techniques. Since the f, f1, and f2 values are higher in the fetal part compared to the maternal part, we can set thresholds to separate these regions.

###Fetal & maternal masks

### Medie ROI
"""

fetal_mask = fetal_mask_data
maternal_mask = maternal_mask_data
background_mask = background_mask_data


bool_fetal = fetal_mask != 0
dwi_fetal = dwi_data [bool_fetal,:]

bool_maternal = maternal_mask!= 0
dwi_maternal = dwi_data [bool_maternal,:]

bool_background = background_mask != 0
dwi_background = dwi_data [bool_background,:]

fetal_mean = np.mean(dwi_fetal, axis=0)
maternal_mean = np.mean(dwi_maternal,  axis=0)
fetal_error = np.std(dwi_fetal, axis=0)/np.sqrt(dwi_fetal.shape[1])
maternal_error = np.std(dwi_maternal, axis=0)/np.sqrt(dwi_maternal.shape[1])

print(fetal_mean)
print(fetal_error)
print("\n")
print(maternal_mean)
print(maternal_error)

"""###SNR maternal & fetal"""

SNR_f = fetal_mean/np.std(dwi_background, axis=0)
SNR_m = maternal_mean/np.std(dwi_background, axis=0)

print("SNR_f =", SNR_f)
print("SNR_m =", SNR_m)

b_SNR = np.array([0, 0.01, 0.03, 0.05, 0.075, 0.1, 0.2, 0.4, 0.7, 1.0]) * 1000  # in s/mm^2

plt.figure(figsize=(10, 6))
plt.plot(b_SNR, SNR_f, 'o-', label='SNR fetal', color='blue')
plt.plot(b_SNR, SNR_m, 's-', label='SNR maternal', color='red')

# Aggiunta di titolo e etichette
plt.title('SNR for fetal and maternal ROIs', fontsize=14, fontweight='bold')
plt.xlabel('b-values ($s/mm^2$)', fontsize=12)
plt.ylabel('SNR', fontsize=12)
plt.legend()

plt.savefig("SNR.pdf")

# Visualizzazione del grafico
plt.show()

"""From the graph, we can observe some key trends in the Signal-to-Noise Ratio measurements for fetal and maternal ROIs, as a function of $b$-values:

1. **General Trend**:
   - Both SNR values (fetal and maternal) tend to decrease with the increase in $b$-values. This behavior is expected as diffusion signals generally decrease with increasing $b$-values, reducing the signal-to-noise ratio.

2. **Differences between Fetal and Maternal SNR**:
   - Maternal SNR values are generally higher than fetal SNR values for all $b$-values. This might indicate that the maternal signal is less subject to noise compared to the fetal signal, or that maternal tissues have different diffusion properties than fetal tissues.

##Monoexponential

###Fit sulla **fetal roi** della maschera usando il modello monoexponential
"""

# Fit sulla media della maschera usando il modello monoexponential

# Calcola la media della ROI fetale per ciascun b-value
mean_dwi_norm_fetal_mono = fetal_mean

# Inizializza i parametri di fitting
init_mono_mean_fetal = [0.1, mean_dwi_norm_fetal_mono[0]]  # [D, S0]
bounds_mono_mean_fetal = ([0.01, 0], [3, np.inf])  # Limiti dei parametri D e S0

try:
    # Eseguo il fit utilizzando curve_fit e x ottenere i parametri ottimali e la matrice di covarianza
    popt_mono_mean_fetal, pcov_mono_mean_fetal = curve_fit(
        monoexponential_model,
        b_values,
        mean_dwi_norm_fetal_mono,#[-4:],  # Usiamo solo gli ultimi 4 valori di b o no?
        sigma=fetal_error,
        p0=init_mono_mean_fetal,
        bounds=bounds_mono_mean_fetal
    )

    # Calcola l'incertezza dei parametri di fitting
    uncertainties_mono_fetal = uncertainty_monoexponential(b_values, *popt_mono_mean_fetal, pcov_mono_mean_fetal)

    print("Parametri ottimali (fetal ROI) per il modello monoexponential, D e S0:", popt_mono_mean_fetal)
    print("\nIncertezze dei parametri (fetal ROI) per il modello monoexponential:", uncertainties_mono_fetal)

except RuntimeError:
    print("RuntimeError: il fit non converge per la fetal ROI.")

# Calcola il numero di parametri del modello monoexponential ed N_b
num_params_mono_fetal = k_mono  # Numero di parametri nel modello monoexponential
N_b_mono_fetal = len(b_values)

# Calcola il mean squared error (MSE)
mean_squared_error_mono_fetal = np.mean((mean_dwi_norm_fetal_mono - monoexponential_model(b_values, *popt_mono_mean_fetal)) ** 2)

# Calcola l'AIC utilizzando la formula
aic_mono_fetal = calculate_AIC(mean_squared_error_mono_fetal, num_params_mono_fetal, N_b_mono_fetal)

print("\nAIC per il modello monoexponential sulla fetal ROI:", aic_mono_fetal)

"""###Fit sulla **maternal roi** della maschera usando il modello monoexponential"""

# Calcola la media della ROI materna per ciascun b-value
mean_dwi_norm_maternal_mono = maternal_mean

# Inizializza i parametri di fitting
init_mono_mean_maternal = [0.1, mean_dwi_norm_maternal_mono[0]]  # [D, S0]
bounds_mono_mean_maternal = ([0.01, 0], [3, np.inf])  # Limiti dei parametri

try:
    # Esegui il fit utilizzando curve_fit e ottieni i parametri ottimali e la matrice di covarianza
    popt_mono_mean_maternal, pcov_mono_mean_maternal = curve_fit(
        monoexponential_model,
        b_values,
        mean_dwi_norm_maternal_mono,#[-4:],  # Usiamo solo gli ultimi 4 valori di b
        sigma=maternal_error,
        p0=init_mono_mean_maternal,
        bounds=bounds_mono_mean_maternal
    )

    # Calcola l'incertezza dei parametri di fitting
    uncertainties_mono_maternal = uncertainty_monoexponential(b_values, *popt_mono_mean_maternal, pcov_mono_mean_maternal)

    print("Parametri ottimali (maternal ROI) per il modello monoexponential, D e S0:",popt_mono_mean_maternal)
    print("\nIncertezze dei parametri (maternal ROI) per il modello monoexponential:", uncertainties_mono_maternal)

except RuntimeError:
    print("RuntimeError: il fit non converge per la maternal ROI.")

# Calcola il numero di parametri del modello monoexponential ed N_b
num_params_mono_maternal = k_mono  # Numero di parametri nel modello monoexponential
N_b_mono_maternal = len(b_values)

# Calcola il mean squared error (MSE)
mean_squared_error_mono_maternal = np.mean((mean_dwi_norm_maternal_mono - monoexponential_model(b_values, *popt_mono_mean_maternal)) ** 2)

# Calcola l'AIC utilizzando la formula
aic_mono_maternal = calculate_AIC(mean_squared_error_mono_maternal, num_params_mono_maternal, N_b_mono_maternal)

print("\nAIC per il modello monoexponential sulla maternal ROI:", aic_mono_maternal)

"""##IVIM

###Fit sulla **fetal roi** della maschera usando il modello IVIM
"""

# Calcola la media della ROI fetale per ciascun b-value
mean_dwi_norm_fetal_IVIM = fetal_mean

# Inizializza il modello IVIM con i parametri medi calcolati dalla fetal ROI
mean_D_fetal_ivim = popt_mono_mean_fetal[0]
#mean_D_fetal_ivim = np.mean(param_maps_monoexponential['D'][fetal_mask])
ivim_model_fetal = IVIM(mean_D_fetal_ivim)

# Inizializza i parametri di fitting
init_ivim_mean_fetal = [0.00000001, 100, mean_dwi_norm_fetal_IVIM[0]]  # [f, D_star, S0]
bounds_ivim_mean_fetal = ([0.00000001, 5, 0], [1, 10000, np.inf])  # Limiti dei parametri

try:
    # Eseguo fit utilizzando curve_fit e ottieni i parametri ottimali e la matrice di covarianza
    popt_ivim_mean_fetal, pcov_ivim_mean_fetal = curve_fit(
        ivim_model_fetal.function,
        b_IVIM,
        mean_dwi_norm_fetal_IVIM,
        sigma=fetal_error,
        p0=init_ivim_mean_fetal,
        bounds=bounds_ivim_mean_fetal
    )

    # Calcola l'incertezza dei parametri di fitting
    uncertainties_ivim_fetal = ivim_model_fetal.uncertainty(b_IVIM, pcov_ivim_mean_fetal)

    print("Parametri ottimali (fetal ROI) per IVIM [f, D_star, S0]:", popt_ivim_mean_fetal)
    print("\nIncertezze dei parametri (fetal ROI) per IVIM:", uncertainties_ivim_fetal)

except RuntimeError:
    print("RuntimeError: il fit non converge per la fetal ROI.")

# Calcola il numero di parametri del modello IVIM ed N_b
num_params_ivim_fetal = k_IVIM  # Numero di parametri nel modello IVIM, sono 3: f, D* & So
N_b_fetal = len(b_IVIM)

# Calcola il mean squared error (MSE)
mean_squared_error_ivim_fetal = np.mean((mean_dwi_norm_fetal_IVIM - ivim_model_fetal.function(b_IVIM, *popt_ivim_mean_fetal)) ** 2)

# Calcola l'AIC utilizzando la formula
aic_ivim_fetal = calculate_AIC(mean_squared_error_ivim_fetal, num_params_ivim_fetal, N_b_fetal)

print("\nAIC per il modello IVIM sulla fetal ROI:", aic_ivim_fetal)

"""###Fit sulla **maternal roi** della maschera usando il modello IVIM"""

# Calcola la media della ROI materna per ciascun b-value
mean_dwi_norm_maternal_IVIM = maternal_mean

# Inizializza il modello IVIM con i parametri medi calcolati dalla ROI materna
mean_D_maternal_ivim = popt_mono_mean_maternal[0]
ivim_model_maternal = IVIM(mean_D_maternal_ivim)

# Inizializza i parametri di fitting
init_ivim_mean_maternal = [0.00000001, 100, mean_dwi_norm_maternal_IVIM[0]]  # [f, D_star, S0]
bounds_ivim_mean_maternal = ([0.00000001, 5, 0], [1, 10000, np.inf])  # Limiti dei parametri

try:
    # Esegui il fit utilizzando curve_fit e ottieni i parametri ottimali e la matrice di covarianza
    popt_ivim_mean_maternal, pcov_ivim_mean_maternal = curve_fit(
        ivim_model_maternal.function,
        b_IVIM,
        mean_dwi_norm_maternal_IVIM,
        sigma=maternal_error,
        p0=init_ivim_mean_maternal,
        bounds=bounds_ivim_mean_maternal
    )

    # Calcola l'incertezza dei parametri di fitting
    uncertainties_ivim_maternal = ivim_model_maternal.uncertainty(b_IVIM, pcov_ivim_mean_maternal)

    print("Parametri ottimali (maternal ROI) per IVIM [f, D_star, S0]:", popt_ivim_mean_maternal)
    print("\nIncertezze dei parametri (maternal ROI) per IVIM:", uncertainties_ivim_maternal)

except RuntimeError:
    print("RuntimeError: il fit non converge per la maternal ROI.")

# Calcola il numero di parametri del modello IVIM ed N_b
num_params_ivim_maternal = k_IVIM  # Numero di parametri nel modello IVIM
N_b_maternal = len(b_IVIM)

# Calcola il mean squared error (MSE)
mean_squared_error_ivim_maternal = np.mean((mean_dwi_norm_maternal_IVIM - ivim_model_maternal.function(b_IVIM, *popt_ivim_mean_maternal)) ** 2)

# Calcola l'AIC utilizzando la formula
aic_ivim_maternal = calculate_AIC(mean_squared_error_ivim_maternal, num_params_ivim_maternal, N_b_maternal)

print("\nAIC per il modello IVIM sulla maternal ROI:", aic_ivim_maternal)

"""##Two-perfusion

###Fit sulla **fetal roi** della maschera usando il modello Two-Perfusion
"""

# Calcola la media della ROI fetale per ciascun b-value
mean_dwi_norm_fetal_2perf = fetal_mean

# Inizializza il modello Perfusion con i parametri medi calcolati dalla fetal ROI
mean_D_fetal = popt_mono_mean_fetal[0]
mean_f_fetal = popt_ivim_mean_fetal[0]
#mean_alpha_fetal = popt_ivim_mean_fetal[-1]

perfusion_model_fetal = Perfusion(mean_D_fetal, mean_f_fetal)

# Inizializza i parametri di fitting
init_perfusion_mean_fetal = [100, 10, 0, mean_dwi_norm_fetal_2perf[0]]
bounds_perfusion_mean_fetal = ([100, 5, 0, 0], [10000, 100, mean_f_fetal, np.inf]) #D1*, D2*, f1, S0

try:
    # Esegui il fit utilizzando curve_fit e ottieni i parametri ottimali e la matrice di covarianza
    popt_mean_fetal_2perf, pcov_mean_fetal = curve_fit(
        perfusion_model_fetal.function2,
        b_perfusion,
        mean_dwi_norm_fetal_2perf,
        sigma=fetal_error,
        p0=init_perfusion_mean_fetal,
        bounds=bounds_perfusion_mean_fetal
    )

    # Calcola l'incertezza dei parametri di fitting
    uncertainties_fetal = perfusion_model_fetal.uncertainty(b_perfusion, pcov_mean_fetal)

    print("Parametri ottimali (fetal ROI) [D1*, D2*, f1, S0]:", popt_mean_fetal_2perf)
    print("\nIncertezze dei parametri (fetal ROI):", uncertainties_fetal)

except RuntimeError:
    print("RuntimeError: il fit non converge per la fetal ROI.")

# Calcola il mean squared error (MSE) utilizzando i dati della fetal ROI e i parametri ottimizzati
MSE_perfusion_fetal = np.mean((mean_dwi_norm_fetal_2perf - perfusion_model_fetal.function2(b_perfusion, *popt_mean_fetal_2perf)) ** 2)

# Calcola l'AIC utilizzando la formula con MSE e k
aic_perfusion_fetal = calculate_AIC(MSE_perfusion_fetal, k_perfusion, N_b_perf)

print("AIC per il modello Two-Perfusion sulla fetal ROI:", aic_perfusion_fetal)

"""###Fit sulla **maternal roi** della maschera usando il modello Two-Perfusion"""

# Calculate the mean of the DWI signal for each b-value within the maternal mask
mean_dwi_norm_maternal_2perf = maternal_mean

# Initialize the Perfusion model with the mean parameters calculated from the maternal ROI
mean_D_maternal = popt_mono_mean_maternal[0]
mean_f_maternal = popt_ivim_mean_maternal[0]
#mean_alpha_maternal = popt_ivim_mean_maternal[-1]

perfusion_model_maternal = Perfusion(mean_D_maternal, mean_f_maternal)

# Initialize the fitting parameters
init_perfusion_mean_maternal = [100, 10, 0, mean_dwi_norm_maternal_2perf[0]]
bounds_perfusion_mean_maternal = ([100, 5, 0, 0], [10000, 100, mean_f_maternal, np.inf])

try:
    # Perform the fit using curve_fit and obtain the optimal parameters and covariance matrix
    popt_mean_maternal_2perf, pcov_mean_maternal = curve_fit(
        perfusion_model_maternal.function2,
        b_perfusion,
        mean_dwi_norm_maternal_2perf,
        sigma=maternal_error,
        p0=init_perfusion_mean_maternal,
        bounds=bounds_perfusion_mean_maternal
    )

    # Calculate the uncertainty of the fitting parameters
    uncertainties_maternal = perfusion_model_maternal.uncertainty(b_perfusion, pcov_mean_maternal)

    print("Optimal parameters (maternal ROI) [D1*, D2*, f1, S0]:", popt_mean_maternal_2perf)
    print("\nUncertainties of the parameters (maternal ROI):", uncertainties_maternal)

except RuntimeError:
    print("RuntimeError: the fit does not converge for the maternal ROI.")

# Calculate the mean squared error (MSE) using the maternal ROI data and the optimized parameters
MSE_perfusion_maternal = np.mean((mean_dwi_norm_maternal_2perf - perfusion_model_maternal.function2(b_perfusion, *popt_mean_maternal_2perf)) ** 2)

# Calculate the AIC using the formula with MSE and k
aic_perfusion_maternal = calculate_AIC(MSE_perfusion_maternal, k_perfusion, N_b_perf)

print("AIC for the Two-Perfusion model on the maternal ROI:", aic_perfusion_maternal)

"""##Results AIC
Akaike weights:

$w_i(AIC) = \frac{e^{-\frac{1}{2}\Delta_i(AIC)}}{\sum_{k=1}^{K}e^{-\frac{1}{2}\Delta_k(AIC)}}$,

where: $\Delta_i(AIC) = AIC_i - \min(AIC)$

###ROI fetale
"""

# Calcola ΔAIC e i pesi dei modelli per la ROI fetale
delta_aic_two_perfusion_fetal = aic_perfusion_fetal - min(aic_perfusion_fetal, aic_ivim_fetal, aic_mono_fetal)
delta_aic_ivim_fetal = aic_ivim_fetal - min(aic_perfusion_fetal, aic_ivim_fetal, aic_mono_fetal)
delta_aic_mono_fetal = aic_mono_fetal - min(aic_perfusion_fetal, aic_ivim_fetal, aic_mono_fetal)

weight_two_perfusion_fetal = np.exp(-0.5 * delta_aic_two_perfusion_fetal)
weight_ivim_fetal = np.exp(-0.5 * delta_aic_ivim_fetal)
weight_mono_fetal = np.exp(-0.5 * delta_aic_mono_fetal)

sum_weights_fetal = weight_two_perfusion_fetal + weight_ivim_fetal + weight_mono_fetal
w_two_perfusion_fetal = weight_two_perfusion_fetal / sum_weights_fetal
w_ivim_fetal = weight_ivim_fetal / sum_weights_fetal
w_mono_fetal = weight_mono_fetal / sum_weights_fetal

print("Delta AIC e pesi dei modelli per la fetal ROI:")
print("ΔAIC Two-Perfusion:", delta_aic_two_perfusion_fetal)
print("ΔAIC IVIM:", delta_aic_ivim_fetal)
print("ΔAIC Monoexponential:", delta_aic_mono_fetal)
print("\n")

print("Pesi dei modelli per la fetal ROI:")
print("Two-Perfusion:", w_two_perfusion_fetal)
print("IVIM:", w_ivim_fetal)
print("Monoexponential:", w_mono_fetal)

print("\nDifferenze in valori di AIC, per la fetal ROI:")
print("AIC_2perf -AIC_IVIM:", aic_perfusion_fetal-aic_ivim_fetal)
print("AIC_2perf -AIC_mono:", aic_perfusion_fetal-aic_mono_fetal)
print("AIC_2IVIM -AIC_mono:", aic_perfusion_fetal-aic_mono_fetal)

"""###ROI materna"""

# Calcola ΔAIC e i pesi dei modelli per la ROI materna
delta_aic_two_perfusion_maternal = aic_perfusion_maternal - min(aic_perfusion_maternal, aic_ivim_maternal, aic_mono_maternal)
delta_aic_ivim_maternal = aic_ivim_maternal - min(aic_perfusion_maternal, aic_ivim_maternal, aic_mono_maternal)
delta_aic_mono_maternal = aic_mono_maternal - min(aic_perfusion_maternal, aic_ivim_maternal, aic_mono_maternal)

weight_two_perfusion_maternal = np.exp(-0.5 * delta_aic_two_perfusion_maternal)
weight_ivim_maternal = np.exp(-0.5 * delta_aic_ivim_maternal)
weight_mono_maternal = np.exp(-0.5 * delta_aic_mono_maternal)

sum_weights_maternal = weight_two_perfusion_maternal + weight_ivim_maternal + weight_mono_maternal
w_two_perfusion_maternal = weight_two_perfusion_maternal / sum_weights_maternal
w_ivim_maternal = weight_ivim_maternal / sum_weights_maternal
w_mono_maternal = weight_mono_maternal / sum_weights_maternal

print("Delta AIC e pesi dei modelli per la maternal ROI:")
print("ΔAIC Two-Perfusion:", delta_aic_two_perfusion_maternal)
print("ΔAIC IVIM:", delta_aic_ivim_maternal)
print("ΔAIC Monoexponential:", delta_aic_mono_maternal)

print("\nPesi dei modelli per la maternal ROI:")
print("Two-Perfusion:", w_two_perfusion_maternal)
print("IVIM:", w_ivim_maternal)
print("Monoexponential:", w_mono_maternal)

"""##**Plot fit**

###ROI fetale
"""

import numpy as np
import matplotlib.pyplot as plt

dwi_norm_std = fetal_error

plt.figure(figsize=(10, 6))

# Plot experimental data with error bars (thinner blue line)
plt.errorbar(b_values, fetal_mean, yerr=fetal_error, fmt='bo', label='Experimental Data', markersize=4, capsize=3, elinewidth=0.5)

# Plot Two-Perfusion fit
plt.plot(b_perfusion, perfusion_model_fetal.function2(b_perfusion, *popt_mean_fetal_2perf), 'r-', label='Two-Perfusion')

# Plot IVIM fit
plt.plot(b_IVIM, ivim_model_fetal.function(b_IVIM, *popt_ivim_mean_fetal), 'g-', label='IVIM')

# Plot Monoexponential fit
plt.plot(b_values, monoexponential_model(b_values, *popt_mono_mean_fetal), 'm-.', label='Monoexponential')

plt.xlabel('$b$ ($\\times 10^3 s/mm^2$)')
plt.ylabel('S($b$) (a.u.)')
plt.title(r'$\bf{Model\ Fits\ on\ Experimental\ Data\ (Fetal\ ROI)}$', fontsize=15)
plt.legend()
plt.grid(False)

# Save the plot as a PDF
plt.savefig('model_fits_fetal_with_errorbars.pdf')

plt.show()

"""###ROI materna"""

plt.figure(figsize=(10, 6))

# Plot experimental data
#plt.plot(b_values, maternal_mean, 'bo', markersize=5)
plt.errorbar(b_values, maternal_mean, yerr=maternal_error, fmt='bo', label='Experimental Data', markersize=4, capsize=3, elinewidth=0.5)


# Plot Two-Perfusion fit
plt.plot(b_perfusion, perfusion_model_maternal.function2(b_perfusion, *popt_mean_maternal_2perf), 'r-', label='Two-Perfusion')
#plt.plot(b_perfusion, perfusion_model_fetal.function2(b_perfusion, *popt_mean_fetal_2perf), 'r-', label='Two-Perfusion')

# Plot IVIM fit
plt.plot(b_IVIM, ivim_model_maternal.function(b_IVIM, *popt_ivim_mean_maternal,), 'g-', label='IVIM')

# Plot Monoexponential fit
plt.plot(b_values, monoexponential_model(b_values, *popt_mono_mean_maternal), 'm-.', label='Monoexponential')

plt.xlabel('$b$ ($\\times 10^3 s/mm^2$)')
plt.ylabel('S($b$) (a.u.)')
plt.title(r'$\bf{Model\ Fits\ on\ Experimental\ Data\ (Maternal\ ROI)}$', fontsize=15)
plt.legend()
plt.grid(False)

# Save the plot as a PDF
plt.savefig('model_fits_maternal.pdf')

plt.show()

"""#Tabella parametri"""

from tabulate import tabulate

# Calcolo di f2 e degli errori
f2 = popt_ivim_mean_fetal[0] - popt_mean_fetal_2perf[2]
err_f2 = np.sqrt(uncertainties_ivim_fetal[0]**2 + uncertainties_fetal[2]**2)

maternal_diff = popt_ivim_mean_maternal[0] - popt_mean_maternal_2perf[2]
maternal_err_diff = np.sqrt(uncertainties_ivim_maternal[0]**2 + uncertainties_maternal[2]**2)

table_data = [
    ["Fetal ROI", popt_mono_mean_fetal[0], uncertainties_mono_fetal[0],
     popt_ivim_mean_fetal[0], uncertainties_ivim_fetal[0],
     popt_mean_fetal_2perf[2], uncertainties_fetal[2],
     f2, err_f2],

    ["Maternal ROI", popt_mono_mean_maternal[0], uncertainties_mono_maternal[0],
     popt_ivim_mean_maternal[0], uncertainties_ivim_maternal[0],
     popt_mean_maternal_2perf[2], uncertainties_maternal[2],
     maternal_diff, maternal_err_diff]
]

headers = ["ROI", "D", "err_D", "f", "err_f", "f1", "err_f1", "f2", "err_f2"]

print(tabulate(table_data, headers=headers, tablefmt="grid"))

#Per stampare in formato latex:
#print(tabulate(table_data, headers=headers, tablefmt="latex"))

"""#Test del $\chi^2$

##Fetal ROI
"""

import numpy as np
import matplotlib.pyplot as plt

# Supponendo che abbiamo già i seguenti dati e modelli
# b_values: array dei valori b
signal_fetal_mean = fetal_mean
signal_fetal_std = fetal_error
# popt_mean_fetal_2perf: parametri del modello Two-Perfusion
# popt_ivim_mean_fetal: parametri del modello IVIM
# popt_mono_mean_fetal: parametri del modello Monoexponential

# Calcola i valori previsti dai modelli per ogni punto dati
predicted_two_perfusion = perfusion_model_fetal.function2(b_values, *popt_mean_fetal_2perf)
predicted_ivim = ivim_model_fetal.function(b_values, *popt_ivim_mean_fetal)
predicted_mono = monoexponential_model(b_values, *popt_mono_mean_fetal)

# Calcola il chi-quadrato per ogni modello
chi2_two_perfusion = np.sum(((signal_fetal_mean - predicted_two_perfusion) ** 2) / signal_fetal_std ** 2)
chi2_ivim = np.sum(((signal_fetal_mean - predicted_ivim) ** 2) / signal_fetal_std ** 2)
chi2_mono = np.sum(((signal_fetal_mean - predicted_mono) ** 2) / signal_fetal_std ** 2)

# Calcola i gradi di libertà per ogni modello
# Gradi di libertà = numero di punti dati - numero di parametri del modello
dof_two_perfusion = len(b_values) - len(popt_mean_fetal_2perf)
dof_ivim = len(b_values) - len(popt_ivim_mean_fetal)
dof_mono = len(b_values) - len(popt_mono_mean_fetal)

# Normalizza i valori di chi-quadrato
chi2_normalized_two_perfusion = chi2_two_perfusion / dof_two_perfusion
chi2_normalized_ivim = chi2_ivim / dof_ivim
chi2_normalized_mono = chi2_mono / dof_mono

print("Chi-Quadrato e Chi-Quadrato Normalizzato per la ROI fetale:")
print("Two-Perfusion: Chi-Quadrato =", chi2_two_perfusion, ", Chi-Quadrato Normalizzato =", chi2_normalized_two_perfusion)
print("IVIM: Chi-Quadrato =", chi2_ivim, ", Chi-Quadrato Normalizzato =", chi2_normalized_ivim)
print("Monoexponential: Chi-Quadrato =", chi2_mono, ", Chi-Quadrato Normalizzato =", chi2_normalized_mono)

from scipy.stats import chi2
# Calcola la probabilità associata a ciascun valore di chi-quadrato
p_value_two_perfusion = 1 - chi2.cdf(chi2_two_perfusion, dof_two_perfusion)
p_value_ivim = 1 - chi2.cdf(chi2_ivim, dof_ivim)
p_value_mono = 1 - chi2.cdf(chi2_mono, dof_mono)

print("Probabilità associate ai valori di Chi-Quadrato per la ROI fetale:")
print("Two-Perfusion: p-value =", p_value_two_perfusion)
print("IVIM: p-value =", p_value_ivim)
print("Monoexponential: p-value =", p_value_mono)

"""##Maternal ROI"""

# b_values: array of b-values
signal_maternal_mean = maternal_mean
signal_maternal_std = maternal_error
# popt_mean_maternal_2perf: parameters of the Two-Perfusion model
# popt_ivim_mean_maternal: parameters of the IVIM model
# popt_mono_mean_maternal: parameters of the Monoexponential model

# Calculate predicted values for each model for each data point
predicted_two_perfusion_maternal = perfusion_model_maternal.function2(b_values, *popt_mean_maternal_2perf)
predicted_ivim_maternal = ivim_model_maternal.function(b_values, *popt_ivim_mean_maternal)
predicted_mono_maternal = monoexponential_model(b_values, *popt_mono_mean_maternal)

# Calculate chi-squared for each model
chi2_two_perfusion_maternal = np.sum(((signal_maternal_mean - predicted_two_perfusion_maternal) ** 2) / signal_maternal_std ** 2)
chi2_ivim_maternal = np.sum(((signal_maternal_mean - predicted_ivim_maternal) ** 2) / signal_maternal_std ** 2)
chi2_mono_maternal = np.sum(((signal_maternal_mean - predicted_mono_maternal) ** 2) / signal_maternal_std ** 2)

# Calculate degrees of freedom for each model
dof_two_perfusion_maternal = len(b_values) - len(popt_mean_maternal_2perf)
dof_ivim_maternal = len(b_values) - len(popt_ivim_mean_maternal)
dof_mono_maternal = len(b_values) - len(popt_mono_mean_maternal)

# Normalize chi-squared values
chi2_normalized_two_perfusion_maternal = chi2_two_perfusion_maternal / dof_two_perfusion_maternal
chi2_normalized_ivim_maternal = chi2_ivim_maternal / dof_ivim_maternal
chi2_normalized_mono_maternal = chi2_mono_maternal / dof_mono_maternal

print("Chi-Squared and Normalized Chi-Squared for the Maternal ROI:")
print("Two-Perfusion: Chi-Squared =", chi2_two_perfusion_maternal, ", Normalized Chi-Squared =", chi2_normalized_two_perfusion_maternal)
print("IVIM: Chi-Squared =", chi2_ivim_maternal, ", Normalized Chi-Squared =", chi2_normalized_ivim_maternal)
print("Monoexponential: Chi-Squared =", chi2_mono_maternal, ", Normalized Chi-Squared =", chi2_normalized_mono_maternal)

# Calculate the p-values associated with each chi-squared value
p_value_two_perfusion_maternal = 1 - chi2.cdf(chi2_two_perfusion_maternal, dof_two_perfusion_maternal)
p_value_ivim_maternal = 1 - chi2.cdf(chi2_ivim_maternal, dof_ivim_maternal)
p_value_mono_maternal = 1 - chi2.cdf(chi2_mono_maternal, dof_mono_maternal)

print("P-values associated with Chi-Squared values for the Maternal ROI:")
print("Two-Perfusion: p-value =", p_value_two_perfusion_maternal)
print("IVIM: p-value =", p_value_ivim_maternal)
print("Monoexponential: p-value =", p_value_mono_maternal)

"""#Test Kolmogorov-Smirnov

Il p-value indica la probabilità che le differenze osservate tra le distribuzioni siano dovute al caso. Un p-value alto (tipicamente maggiore di 0.05) suggerisce che non ci sono prove sufficienti per rifiutare l'ipotesi nulla, ossia che i dati osservati provengano dalla stessa distribuzione dei dati previsti dal modello.

##**Fetal**
"""

from scipy.stats import kstest

signal_fetal_mean = fetal_mean
signal_fetal_std = fetal_error
# popt_mean_fetal_2perf: parametri del modello Two-Perfusion
# popt_ivim_mean_fetal: parametri del modello IVIM
# popt_mono_mean_fetal: parametri del modello Monoexponential

#  valori previsti dai modelli per ogni punto dati
predicted_two_perfusion = perfusion_model_fetal.function2(b_values, *popt_mean_fetal_2perf)
predicted_ivim = ivim_model_fetal.function(b_values, *popt_ivim_mean_fetal)
predicted_mono = monoexponential_model(b_values, *popt_mono_mean_fetal)

# Funzione per il test di Kolmogorov-Smirnov
def perform_ks_test(observed, predicted):
    # Esegui il test di KS confrontando i dati osservati con quelli previsti
    ks_statistic, p_value = kstest(observed, 'norm', args=(np.mean(predicted), np.std(predicted)))
    return ks_statistic, p_value

# test di Kolmogorov-Smirnov per ogni modello
ks_statistic_two_perfusion, p_value_two_perfusion = perform_ks_test(signal_fetal_mean, predicted_two_perfusion)
ks_statistic_ivim, p_value_ivim = perform_ks_test(signal_fetal_mean, predicted_ivim)
ks_statistic_mono, p_value_mono = perform_ks_test(signal_fetal_mean, predicted_mono)

print("Test di Kolmogorov-Smirnov per la ROI fetale:")
print("Two-Perfusion: KS Statistic =", ks_statistic_two_perfusion, ", p-value =", p_value_two_perfusion)
print("IVIM: KS Statistic =", ks_statistic_ivim, ", p-value =", p_value_ivim)
print("Monoexponential: KS Statistic =", ks_statistic_mono, ", p-value =", p_value_mono)

"""##**Maternal**"""

signal_maternal_mean = maternal_mean
signal_maternal_std = maternal_error

predicted_two_perfusion_maternal = perfusion_model_maternal.function2(b_values, *popt_mean_maternal_2perf)
predicted_ivim_maternal = ivim_model_maternal.function(b_values, *popt_ivim_mean_maternal)
predicted_mono_maternal = monoexponential_model(b_values, *popt_mono_mean_maternal)

ks_statistic_two_perfusion_maternal, p_value_two_perfusion_maternal = perform_ks_test(signal_maternal_mean, predicted_two_perfusion_maternal)
ks_statistic_ivim_maternal, p_value_ivim_maternal = perform_ks_test(signal_maternal_mean, predicted_ivim_maternal)
ks_statistic_mono_maternal, p_value_mono_maternal = perform_ks_test(signal_maternal_mean, predicted_mono_maternal)

print("Test di Kolmogorov-Smirnov per la ROI materna:")
print("Two-Perfusion: KS Statistic =", ks_statistic_two_perfusion_maternal, ", p-value =", p_value_two_perfusion_maternal)
print("IVIM: KS Statistic =", ks_statistic_ivim_maternal, ", p-value =", p_value_ivim_maternal)
print("Monoexponential: KS Statistic =", ks_statistic_mono_maternal, ", p-value =", p_value_mono_maternal)

"""#**Parte 3**: fit fetal & maternal $\forall$ placenta"""

TOT_NUM_OF_PLACENTAS = 15

import os
import numpy as np
import pandas as pd
import nibabel as nib
import matplotlib.pyplot as plt
from tabulate import tabulate
from scipy.optimize import curve_fit
from scipy.stats import chi2
from scipy.stats import pearsonr

# Definisci le funzioni dei modelli (monoexponential, IVIM, Two-Perfusion)
def monoexponential_model(b, D, S0):
    return S0 * np.exp(-b * D)

class IVIM:
    def __init__(self, D):
        self.D = D

    def function(self, b, f, D_star, S0):
        return S0 * (f * np.exp(-b * D_star) + (1 - f) * np.exp(-b * self.D))

    def uncertainty(self, b, pcov):
        return np.sqrt(np.diag(pcov))

class Perfusion:
    def __init__(self, D, f):
        self.D = D
        self.f = f

    def function2(self, b, D_star1, D_star2, f1, S0):
        f2 = self.f - f1
        return S0 * (f1 * np.exp(-b * D_star1) + f2 * np.exp(-b * D_star2) + (1 - self.f) * np.exp(-b * self.D))

    def uncertainty(self, b, pcov):
        return np.sqrt(np.diag(pcov))

# Calcola l'Akaike Information Criterion (AIC)
def calculate_AIC(MSE, k, N_b):
    return N_b * np.log(MSE) + 2 * k * (k + 1) / (N_b - k - 1)

# Calcola la media e la deviazione standard all'interno della ROI
def calculate_mean_and_std(param_map, mask_data):
    mean_roi = np.mean(param_map[mask_data != 0])
    std_roi = np.std(param_map[mask_data != 0], ddof=1) / np.sqrt(np.count_nonzero(mask_data))
    return mean_roi, std_roi

# Numero di parametri dei modelli
k_perfusion = 4
k_IVIM = 3
k_mono = 2

# Numero di b-values utilizzati nel fitting
N_b_perf = 10
N_b_IVIM = 10
N_b_mono = 4

file_path = "/content/drive/MyDrive/LAB_2/1.5T/DB_placente_15.xlsx"
df = pd.read_excel(file_path)
GA_weeks = df.iloc[0:15]['GA (week)'].values

def calculate_pearson_correlation(x, y):
    correlation, p_value = pearsonr(x, y)
    return correlation, p_value

base_path = "/content/drive/MyDrive/LAB_2/1.5T"
# Inizializza le liste per memorizzare i parametri dei fit e le incertezze

#Inizializzo per test di PEARSON
f_fetal = []
err_f_fetal = []
f_maternal = []
err_f_maternal = []

f1_fetal = []
err_f1_fetal = []
f1_maternal = []
err_f1_maternal = []


f2_fetal = []
err_f2_fetal = []
f2_maternal = []
err_f2_maternal = []


D_fetal = []
err_D_fetal = []
D_maternal = []
err_D_maternal = []

for i in range(1, TOT_NUM_OF_PLACENTAS + 1):
    placenta_path = os.path.join(base_path, f"{i}")
    fetal_mask_path = load_nii_file(placenta_path, "fetal_mask.nii")
    maternal_mask_path = load_nii_file(placenta_path, "maternal_mask.nii")
    dwi_image_path = load_nii_file(placenta_path, "dwi.nii")

    fetal_mask = fetal_mask_path.get_fdata()
    maternal_mask = maternal_mask_path.get_fdata()
    dwi_data = dwi_image_path.get_fdata()

    bool_fetal = fetal_mask != 0
    dwi_fetal = dwi_data[bool_fetal, :]

    bool_maternal = maternal_mask != 0
    dwi_maternal = dwi_data[bool_maternal, :]

    fetal_mean = np.mean(dwi_fetal, axis=0)
    maternal_mean = np.mean(dwi_maternal, axis=0)
    fetal_error = np.std(dwi_fetal, axis=0) / np.sqrt(dwi_fetal.shape[1])
    maternal_error = np.std(dwi_maternal, axis=0) / np.sqrt(dwi_maternal.shape[1])

    # Fit modelli e calcolo AIC per ROI fetale
    mean_dwi_norm_fetal_mono = fetal_mean
    init_mono_mean_fetal = [0.1, mean_dwi_norm_fetal_mono[0]]
    bounds_mono_mean_fetal = ([0.01, 0], [3, np.inf])

    try:
        popt_mono_mean_fetal, pcov_mono_mean_fetal = curve_fit(
            monoexponential_model,
            b_values,
            mean_dwi_norm_fetal_mono,
            sigma=fetal_error,
            p0=init_mono_mean_fetal,
            bounds=bounds_mono_mean_fetal
        )
        uncertainties_mono_fetal = uncertainty_monoexponential(b_values, *popt_mono_mean_fetal, pcov_mono_mean_fetal)
    except RuntimeError:
        print("RuntimeError: il fit non converge per la fetal ROI.")
        continue

    num_params_mono_fetal = k_mono
    N_b_mono_fetal = len(b_values)
    mean_squared_error_mono_fetal = np.mean((mean_dwi_norm_fetal_mono - monoexponential_model(b_values, *popt_mono_mean_fetal)) ** 2)
    aic_mono_fetal = calculate_AIC(mean_squared_error_mono_fetal, num_params_mono_fetal, N_b_mono_fetal)

    # Modello IVIM
    mean_dwi_norm_fetal_IVIM = fetal_mean
    mean_D_fetal_ivim = popt_mono_mean_fetal[0]
    ivim_model_fetal = IVIM(mean_D_fetal_ivim)
    init_ivim_mean_fetal = [0.00000001, 100, mean_dwi_norm_fetal_IVIM[0]]
    bounds_ivim_mean_fetal = ([0.00000001, 5, 0], [1, 10000, np.inf])

    try:
        popt_ivim_mean_fetal, pcov_ivim_mean_fetal = curve_fit(
            ivim_model_fetal.function,
            b_IVIM,
            mean_dwi_norm_fetal_IVIM,
            sigma=fetal_error,
            p0=init_ivim_mean_fetal,
            bounds=bounds_ivim_mean_fetal
        )
        uncertainties_ivim_fetal = ivim_model_fetal.uncertainty(b_IVIM, pcov_ivim_mean_fetal)
    except RuntimeError:
        print("RuntimeError: il fit non converge per la fetal ROI.")
        continue

    num_params_ivim_fetal = k_IVIM
    N_b_fetal = len(b_IVIM)
    mean_squared_error_ivim_fetal = np.mean((mean_dwi_norm_fetal_IVIM - ivim_model_fetal.function(b_IVIM, *popt_ivim_mean_fetal)) ** 2)
    aic_ivim_fetal = calculate_AIC(mean_squared_error_ivim_fetal, num_params_ivim_fetal, N_b_fetal)

    # Modello Two-Perfusion
    mean_dwi_norm_fetal_2perf = fetal_mean
    mean_D_fetal = popt_mono_mean_fetal[0]
    mean_f_fetal = popt_ivim_mean_fetal[0]
    perfusion_model_fetal = Perfusion(mean_D_fetal, mean_f_fetal)
    init_perfusion_mean_fetal = [100, 10, 0, mean_dwi_norm_fetal_2perf[0]]
    bounds_perfusion_mean_fetal = ([100, 5, 0, 0], [10000, 100, mean_f_fetal, np.inf])

    try:
        popt_mean_fetal_2perf, pcov_mean_fetal = curve_fit(
            perfusion_model_fetal.function2,
            b_perfusion,
            mean_dwi_norm_fetal_2perf,
            sigma=fetal_error,
            p0=init_perfusion_mean_fetal,
            bounds=bounds_perfusion_mean_fetal
        )
        uncertainties_fetal = perfusion_model_fetal.uncertainty(b_perfusion, pcov_mean_fetal)
    except RuntimeError:
        print("RuntimeError: il fit non converge per la fetal ROI.")
        continue

    MSE_perfusion_fetal = np.mean((mean_dwi_norm_fetal_2perf - perfusion_model_fetal.function2(b_perfusion, *popt_mean_fetal_2perf)) ** 2)
    aic_perfusion_fetal = calculate_AIC(MSE_perfusion_fetal, k_perfusion, N_b_perf)

    # Calcolo ΔAIC e pesi dei modelli per la ROI fetale
    delta_aic_two_perfusion_fetal = aic_perfusion_fetal - min(aic_perfusion_fetal, aic_ivim_fetal, aic_mono_fetal)
    delta_aic_ivim_fetal = aic_ivim_fetal - min(aic_perfusion_fetal, aic_ivim_fetal, aic_mono_fetal)
    delta_aic_mono_fetal = aic_mono_fetal - min(aic_perfusion_fetal, aic_ivim_fetal, aic_mono_fetal)

    weight_two_perfusion_fetal = np.exp(-0.5 * delta_aic_two_perfusion_fetal)
    weight_ivim_fetal = np.exp(-0.5 * delta_aic_ivim_fetal)
    weight_mono_fetal = np.exp(-0.5 * delta_aic_mono_fetal)

    sum_weights_fetal = weight_two_perfusion_fetal + weight_ivim_fetal + weight_mono_fetal
    w_two_perfusion_fetal = weight_two_perfusion_fetal / sum_weights_fetal
    w_ivim_fetal = weight_ivim_fetal / sum_weights_fetal
    w_mono_fetal = weight_mono_fetal / sum_weights_fetal

    # Output dei risultati
    print(f"Placenta {i}:")
    #print("ΔAIC Two-Perfusion:", delta_aic_two_perfusion_fetal)
    #print("ΔAIC IVIM:", delta_aic_ivim_fetal)
    #print("ΔAIC Monoexponential:", delta_aic_mono_fetal)
    print("\nPesi dei modelli per la fetal ROI:")
    print("Two-Perfusion:", w_two_perfusion_fetal)
    print("IVIM:", w_ivim_fetal)
    print("Monoexponential:", w_mono_fetal)

    # Fit modelli e calcolo AIC per ROI materna
    mean_dwi_norm_maternal_mono = maternal_mean
    init_mono_mean_maternal = [0.1, mean_dwi_norm_maternal_mono[0]]
    bounds_mono_mean_maternal = ([0.01, 0], [3, np.inf])

    try:
        popt_mono_mean_maternal, pcov_mono_mean_maternal = curve_fit(
            monoexponential_model,
            b_values,
            mean_dwi_norm_maternal_mono,
            sigma=maternal_error,
            p0=init_mono_mean_maternal,
            bounds=bounds_mono_mean_maternal
        )
        uncertainties_mono_maternal = uncertainty_monoexponential(b_values, *popt_mono_mean_maternal, pcov_mono_mean_maternal)
    except RuntimeError:
        print("RuntimeError: il fit non converge per la maternal ROI.")
        continue

    num_params_mono_maternal = k_mono
    N_b_mono_maternal = len(b_values)
    mean_squared_error_mono_maternal = np.mean((mean_dwi_norm_maternal_mono - monoexponential_model(b_values, *popt_mono_mean_maternal)) ** 2)
    aic_mono_maternal = calculate_AIC(mean_squared_error_mono_maternal, num_params_mono_maternal, N_b_mono_maternal)

    # Modello IVIM
    mean_dwi_norm_maternal_IVIM = maternal_mean
    mean_D_maternal_ivim = popt_mono_mean_maternal[0]
    ivim_model_maternal = IVIM(mean_D_maternal_ivim)
    init_ivim_mean_maternal = [0.00000001, 100, mean_dwi_norm_maternal_IVIM[0]]
    bounds_ivim_mean_maternal = ([0.00000001, 5, 0], [1, 10000, np.inf])

    try:
        popt_ivim_mean_maternal, pcov_ivim_mean_maternal = curve_fit(
            ivim_model_maternal.function,
            b_IVIM,
            mean_dwi_norm_maternal_IVIM,
            sigma=maternal_error,
            p0=init_ivim_mean_maternal,
            bounds=bounds_ivim_mean_maternal
        )
        uncertainties_ivim_maternal = ivim_model_maternal.uncertainty(b_IVIM, pcov_ivim_mean_maternal)
    except RuntimeError:
        print("RuntimeError: il fit non converge per la maternal ROI.")
        continue

    num_params_ivim_maternal = k_IVIM
    N_b_maternal = len(b_IVIM)
    mean_squared_error_ivim_maternal = np.mean((mean_dwi_norm_maternal_IVIM - ivim_model_maternal.function(b_IVIM, *popt_ivim_mean_maternal)) ** 2)
    aic_ivim_maternal = calculate_AIC(mean_squared_error_ivim_maternal, num_params_ivim_maternal, N_b_maternal)

    # Modello Two-Perfusion
    mean_dwi_norm_maternal_2perf = maternal_mean
    mean_D_maternal = popt_mono_mean_maternal[0]
    mean_f_maternal = popt_ivim_mean_maternal[0]
    perfusion_model_maternal = Perfusion(mean_D_maternal, mean_f_maternal)
    init_perfusion_mean_maternal = [100, 10, 0, mean_dwi_norm_maternal_2perf[0]]
    bounds_perfusion_mean_maternal = ([100, 5, 0, 0], [10000, 100, mean_f_maternal, np.inf])

    try:
        popt_mean_maternal_2perf, pcov_mean_maternal = curve_fit(
            perfusion_model_maternal.function2,
            b_perfusion,
            mean_dwi_norm_maternal_2perf,
            sigma=maternal_error,
            p0=init_perfusion_mean_maternal,
            bounds=bounds_perfusion_mean_maternal
        )
        uncertainties_maternal = perfusion_model_maternal.uncertainty(b_perfusion, pcov_mean_maternal)
    except RuntimeError:
        print("RuntimeError: il fit non converge per la maternal ROI.")
        continue

    MSE_perfusion_maternal = np.mean((mean_dwi_norm_maternal_2perf - perfusion_model_maternal.function2(b_perfusion, *popt_mean_maternal_2perf)) ** 2)
    aic_perfusion_maternal = calculate_AIC(MSE_perfusion_maternal, k_perfusion, N_b_perf)

    # Calcolo ΔAIC e pesi dei modelli per la ROI materna
    delta_aic_two_perfusion_maternal = aic_perfusion_maternal - min(aic_perfusion_maternal, aic_ivim_maternal, aic_mono_maternal)
    delta_aic_ivim_maternal = aic_ivim_maternal - min(aic_perfusion_maternal, aic_ivim_maternal, aic_mono_maternal)
    delta_aic_mono_maternal = aic_mono_maternal - min(aic_perfusion_maternal, aic_ivim_maternal, aic_mono_maternal)

    weight_two_perfusion_maternal = np.exp(-0.5 * delta_aic_two_perfusion_maternal)
    weight_ivim_maternal = np.exp(-0.5 * delta_aic_ivim_maternal)
    weight_mono_maternal = np.exp(-0.5 * delta_aic_mono_maternal)

    sum_weights_maternal = weight_two_perfusion_maternal + weight_ivim_maternal + weight_mono_maternal
    w_two_perfusion_maternal = weight_two_perfusion_maternal / sum_weights_maternal
    w_ivim_maternal = weight_ivim_maternal / sum_weights_maternal
    w_mono_maternal = weight_mono_maternal / sum_weights_maternal

    # Output dei risultati
    print(f"Placenta {i}")
    #print("ΔAIC Two-Perfusion:", delta_aic_two_perfusion_maternal)
    #print("ΔAIC IVIM:", delta_aic_ivim_maternal)
    #print("ΔAIC Monoexponential:", delta_aic_mono_maternal)
    #print("\nPesi dei modelli per la maternal ROI:")
    #print("Two-Perfusion:", w_two_perfusion_maternal)
    #print("IVIM:", w_ivim_maternal)
    #print("Monoexponential:", w_mono_maternal)

    # Plot dei risultati per ROI fetale
    """
    plt.figure(figsize=(10, 6))
    plt.errorbar(b_values, fetal_mean, yerr=fetal_error, fmt='bo', label='Experimental Data', markersize=4, capsize=3, elinewidth=0.5)
    plt.plot(b_perfusion, perfusion_model_fetal.function2(b_perfusion, *popt_mean_fetal_2perf), 'r-', label='Two-Perfusion')
    plt.plot(b_IVIM, ivim_model_fetal.function(b_IVIM, *popt_ivim_mean_fetal), 'g-', label='IVIM')
    plt.plot(b_values, monoexponential_model(b_values, *popt_mono_mean_fetal), 'm-.', label='Monoexponential')
    plt.xlabel('$b$ ($\\times 10^3 s/mm^2$)')
    plt.ylabel('S($b$) (a.u.)')
    plt.title(r'$\bf{Model\ Fits\ on\ Experimental\ Data\ (Fetal\ ROI)}$', fontsize=15)
    plt.legend()
    plt.grid(False)
    #plt.savefig(f'model_fits_fetal_with_errorbars_{i}.pdf')
    plt.show()

    # Plot dei risultati per ROI materna
    plt.figure(figsize=(10, 6))
    plt.errorbar(b_values, maternal_mean, yerr=maternal_error, fmt='bo', label='Experimental Data', markersize=4, capsize=3, elinewidth=0.5)
    plt.plot(b_perfusion, perfusion_model_maternal.function2(b_perfusion, *popt_mean_maternal_2perf), 'r-', label='Two-Perfusion')
    plt.plot(b_IVIM, ivim_model_maternal.function(b_IVIM, *popt_ivim_mean_maternal), 'g-', label='IVIM')
    plt.plot(b_values, monoexponential_model(b_values, *popt_mono_mean_maternal), 'm-.', label='Monoexponential')
    plt.xlabel('$b$ ($\\times 10^3 s/mm^2$)')
    plt.ylabel('S($b$) (a.u.)')
    plt.title(r'$\bf{Model\ Fits\ on\ Experimental\ Data\ (Maternal\ ROI)}$', fontsize=15)
    plt.legend()
    plt.grid(False)
    #plt.savefig(f'model_fits_maternal_{i}.pdf')
    plt.show()

    """

    # Tabelle dei risultati
    f2 = popt_ivim_mean_fetal[0] - popt_mean_fetal_2perf[2]
    err_f2 = np.sqrt(uncertainties_ivim_fetal[0]**2 + uncertainties_fetal[2]**2)

    maternal_diff = popt_ivim_mean_maternal[0] - popt_mean_maternal_2perf[2]
    maternal_err_diff = np.sqrt(uncertainties_ivim_maternal[0]**2 + uncertainties_maternal[2]**2)

    table_data = [
        ["Fetal ROI", popt_mono_mean_fetal[0], uncertainties_mono_fetal[0],
         popt_ivim_mean_fetal[0], uncertainties_ivim_fetal[0],
         popt_mean_fetal_2perf[2], uncertainties_fetal[2],
         f2, err_f2],

        ["Maternal ROI", popt_mono_mean_maternal[0], uncertainties_mono_maternal[0],
         popt_ivim_mean_maternal[0], uncertainties_ivim_maternal[0],
         popt_mean_maternal_2perf[2], uncertainties_maternal[2],
         maternal_diff, maternal_err_diff]
    ]

    headers = ["ROI", "D", "err_D", "f", "err_f", "f1", "err_f1", "f2", "err_f2"]

    print(tabulate(table_data, headers=headers, tablefmt="grid"))

    # Mi salvo in un array i valori dei 4 parametri che desidero, per ogni placenta
    f_fetal.append(popt_ivim_mean_fetal[0])
    err_f_fetal.append(uncertainties_ivim_fetal[0])
    f_maternal.append(popt_ivim_mean_maternal[0])
    err_f_maternal.append(uncertainties_ivim_maternal[0])


    f1_fetal.append(popt_mean_fetal_2perf[2])
    err_f1_fetal.append(uncertainties_fetal[2])
    f1_maternal.append(popt_mean_maternal_2perf[2])
    err_f1_maternal.append(uncertainties_maternal[2])

    f2_fetal.append(f2)
    err_f2_fetal.append(err_f2)
    f2_maternal.append(maternal_diff)
    err_f2_maternal.append(maternal_err_diff)

    D_fetal.append(popt_mono_mean_fetal[0])
    err_D_fetal.append(uncertainties_mono_fetal[0])
    D_maternal.append(popt_mono_mean_maternal[0])
    err_D_maternal.append(uncertainties_mono_maternal[0])

    print('-' * 180)  # Stampa una riga di 180 trattini

# Converte le liste in array numpy per facilitare il calcolo
f_fetal = np.array(f_fetal)
err_f_fetal = np.array(err_f_fetal)
f_maternal = np.array(f_maternal)
err_f_maternal = np.array(err_f_maternal)

f1_fetal = np.array(f1_fetal)
err_f1_fetal = np.array(err_f1_fetal)
f1_maternal = np.array(f1_maternal)
err_f1_maternal = np.array(err_f1_maternal)

f2_fetal = np.array(f2_fetal)
err_f2_fetal = np.array(err_f2_fetal)
f2_maternal = np.array(f2_maternal)
err_f2_maternal = np.array(err_f2_maternal)

D_fetal = np.array(D_fetal)
err_D_fetal = np.array(err_D_fetal)
D_maternal = np.array(D_maternal)
err_D_maternal = np.array(err_D_maternal)

# Non è necessario convertire nuovamente gli array numpy già esistenti
# Calcola la media dei parametri e le incertezze
mean_f_fetal = np.mean(f_fetal, axis=0)
mean_err_f_fetal = np.sqrt(np.sum(err_f_fetal**2, axis=0)) / len(err_f_fetal)
mean_f_maternal = np.mean(f_maternal, axis=0)
mean_err_f_maternal = np.sqrt(np.sum(err_f_maternal**2, axis=0)) / len(err_f_maternal)

mean_f1_fetal = np.mean(f1_fetal, axis=0)
mean_err_f1_fetal = np.sqrt(np.sum(err_f1_fetal**2, axis=0)) / len(err_f1_fetal)
mean_f1_maternal = np.mean(f1_maternal, axis=0)
mean_err_f1_maternal = np.sqrt(np.sum(err_f1_maternal**2, axis=0)) / len(err_f1_maternal)

mean_f2_fetal = np.mean(f2_fetal, axis=0)
mean_err_f2_fetal = np.sqrt(np.sum(err_f2_fetal**2, axis=0)) / len(err_f2_fetal)
mean_f2_maternal = np.mean(f2_maternal, axis=0)
mean_err_f2_maternal = np.sqrt(np.sum(err_f2_maternal**2, axis=0)) / len(err_f2_maternal)

mean_D_fetal = np.mean(D_fetal, axis=0)
mean_err_D_fetal = np.sqrt(np.sum(err_D_fetal**2, axis=0)) / len(err_D_fetal)
mean_D_maternal = np.mean(D_maternal, axis=0)
mean_err_D_maternal = np.sqrt(np.sum(err_D_maternal**2, axis=0)) / len(err_D_maternal)

# Calcola f2 e le incertezze per la media
f2_mean_fetal = mean_f_fetal - mean_f1_fetal
err_f2_mean_fetal = np.sqrt(mean_err_f_fetal**2 + mean_err_f1_fetal**2)

f2_mean_maternal = mean_f_maternal - mean_f1_maternal
err_f2_mean_maternal = np.sqrt(mean_err_f_maternal**2 + mean_err_f1_maternal**2)

# Crea la tabella finale
table_data_final = [
    ["Fetal ROI", mean_D_fetal, mean_err_D_fetal,
     mean_f_fetal, mean_err_f_fetal,
     mean_f1_fetal, mean_err_f1_fetal,
     f2_mean_fetal, err_f2_mean_fetal],

    ["Maternal ROI", mean_D_maternal, mean_err_D_maternal,
     mean_f_maternal, mean_err_f_maternal,
     mean_f1_maternal, mean_err_f1_maternal,
     f2_mean_maternal, err_f2_mean_maternal]
]

headers_final = ["ROI", "D", "err_D", "f", "err_f", "f1", "err_f1", "f2", "err_f2"]

print(tabulate(table_data_final, headers=headers_final, tablefmt="grid"))

#TEST DI PERASON E GRAFICI

# Genera i grafici
plt.figure(figsize=(12, 12))

# f vs GA
plt.subplot(2, 2, 1)
plt.scatter(GA_weeks, f_maternal, label='Maternal ROI', color='k')
plt.scatter(GA_weeks, f_fetal, label='Fetal ROI', color='red', marker='v')
plt.xlabel('Gestational Age (weeks)')
plt.ylabel('f')
plt.title('f vs GA')
plt.legend()

# f1 vs GA
plt.subplot(2, 2, 2)
plt.scatter(GA_weeks, f1_maternal, label='Maternal ROI', color='k')
plt.scatter(GA_weeks, f1_fetal, label='Fetal ROI', color='red', marker='v')
plt.xlabel('Gestational Age (weeks)')
plt.ylabel('f1')
plt.title('f1 vs GA')
plt.legend()

# f2 vs GA
plt.subplot(2, 2, 3)
plt.scatter(GA_weeks, f2_maternal, label='Maternal ROI', color='k')
plt.scatter(GA_weeks, f2_fetal, label='Fetal ROI', color='red', marker='v')
plt.xlabel('Gestational Age (weeks)')
plt.ylabel('f2')
plt.title('f2 vs GA')
plt.legend()

# D vs GA
plt.subplot(2, 2, 4)
plt.scatter(GA_weeks, D_maternal , label='Maternal ROI', color='k')  # Conversione a x10^-3 mm^2/s
plt.scatter(GA_weeks, D_fetal , label='Fetal ROI', color='red', marker='v')  # Conversione a x10^-3 mm^2/s
plt.xlabel('Gestational Age (weeks)')
plt.ylabel('D (x10^-3 mm^2/s)')
plt.title('D vs GA')
plt.legend()

plt.tight_layout()
plt.savefig("paramVSga.pdf")
plt.show()

# Calcola le correlazioni e i valori p
correlation_f_maternal, p_value_f_maternal = calculate_pearson_correlation(f_maternal, GA_weeks)
correlation_f_fetal, p_value_f_fetal = calculate_pearson_correlation(f_fetal, GA_weeks)
correlation_f1_maternal, p_value_f1_maternal = calculate_pearson_correlation(f1_maternal, GA_weeks)
correlation_f1_fetal, p_value_f1_fetal = calculate_pearson_correlation(f1_fetal, GA_weeks)
correlation_f2_maternal, p_value_f2_maternal = calculate_pearson_correlation(f2_maternal, GA_weeks)
correlation_f2_fetal, p_value_f2_fetal = calculate_pearson_correlation(f2_fetal, GA_weeks)
correlation_D_maternal, p_value_D_maternal = calculate_pearson_correlation(D_maternal, GA_weeks)
correlation_D_fetal, p_value_D_fetal = calculate_pearson_correlation(D_fetal, GA_weeks)

# Stampa le correlazioni
print(f'Correlation f (maternal) vs GA: r={correlation_f_maternal:.2f}, p={p_value_f_maternal:.2f}')
print(f'Correlation f (fetal) vs GA: r={correlation_f_fetal:.2f}, p={p_value_f_fetal:.2f}')
print(f'Correlation f1 (maternal) vs GA: r={correlation_f1_maternal:.2f}, p={p_value_f1_maternal:.2f}')
print(f'Correlation f1 (fetal) vs GA: r={correlation_f1_fetal:.2f}, p={p_value_f1_fetal:.2f}')
print(f'Correlation f2 (maternal) vs GA: r={correlation_f2_maternal:.2f}, p={p_value_f2_maternal:.2f}')
print(f'Correlation f2 (fetal) vs GA: r={correlation_f2_fetal:.2f}, p={p_value_f2_fetal:.2f}')
print(f'Correlation D (maternal) vs GA: r={correlation_D_maternal:.2f}, p={p_value_D_maternal:.2f}')
print(f'Correlation D (fetal) vs GA: r={correlation_D_fetal:.2f}, p={p_value_D_fetal:.2f}')

"""##altro"""

#in linguaggio latex:
print(tabulate(table_data_final, headers=headers_final, tablefmt="latex"))